ADDITION_TEMPLATES = [
    "{name} has {A} {items}. {pronoun} gets {B} more. How many {items} does {name} have now?",
    "{name} has {A} {items} and buys {B} more. How many {items} does {name} have in total?",
    "There are {A} {items} on a table. Someone adds {B} more. How many {items} are on the table?",
    "{name} picks {A} {items} in the morning and {B} in the afternoon. How many {items} did {name} pick?",
    "A store has {A} {items}. A delivery brings {B} more. How many {items} does the store have now?",
    "{name} has {A} {items}. {name2} gives {name} {B} more. How many {items} does {name} have?",
    "There are {A} {items} in a box. {name} puts {B} more in. How many {items} are in the box?",
    "{name} earns ${A} on Monday and ${B} on Tuesday. How much money did {name} earn in total?",
    "A farmer has {A} {items}. He buys {B} more. How many {items} does the farmer have now?",
    "{name} reads {A} pages before lunch and {B} pages after lunch. How many pages did {name} read?",
    "A jar has {A} {items}. {name} adds {B} more. How many {items} are in the jar now?",
    "{name} walks {A} blocks north and then {B} blocks south. How many blocks did {name} walk in total?",
    "A class has {A} boys and {B} girls. How many students are in the class?",
    "{name} scores {A} points in the first half and {B} in the second half. What is the total score?",
    "A library has {A} books on one shelf and {B} on another. How many books are there in total?",
    "{name} has {A} red {items} and {B} blue {items}. How many {items} does {name} have altogether?",
    "In the morning there are {A} {items}. By evening there are {B} more. How many are there now?",
    "{name} saves ${A} in January and ${B} in February. How much did {name} save in total?",
    "A parking lot has {A} cars. Then {B} more cars arrive. How many cars are in the lot?",
    "{name} collects {A} {items} on Saturday and {B} on Sunday. How many {items} did {name} collect?",
    "A garden has {A} flowers. {name} plants {B} more. How many flowers are in the garden?",
    "{name} has {A} {items} in one pocket and {B} in another. How many {items} in total?",
    "A train has {A} passengers. At the next stop {B} more get on. How many passengers are on the train?",
    "{name} bakes {A} {items} and {name2} bakes {B}. How many {items} did they bake together?",
    "There are {A} birds in a tree. Then {B} more land on it. How many birds are in the tree now?",
    "A pool has {A} liters of water. {name} adds {B} more liters. How many liters are in the pool?",
    "{name} finds {A} {items} at the park and {B} at the beach. How many {items} did {name} find?",
    "A box has {A} {items}. Another box has {B}. How many {items} are there in both boxes?",
    "{name} does {A} push-ups in the morning and {B} in the evening. How many push-ups total?",
    "A zoo has {A} animals. They receive {B} new animals. How many animals does the zoo have now?",
    "{name} has {A} songs on a playlist. {pronoun} adds {B} more. How many songs are on the playlist?",
    "A team has {A} members. Then {B} new people join. How many members does the team have?",
    "{name} types {A} words in the first minute and {B} in the second. How many words total?",
    "A shelf has {A} {items}. {name} puts {B} more on it. How many {items} are on the shelf now?",
    "{name} drives {A} km before lunch and {B} km after. How many km did {name} drive in total?",
    "There are {A} chairs in a room. {name} brings in {B} more. How many chairs are there now?",
    "A bakery makes {A} {items} in the morning and {B} in the afternoon. How many {items} in total?",
    "{name} has ${A} in savings. {pronoun} deposits ${B} more. How much does {name} have now?",
    "A truck carries {A} {items}. Workers load {B} more. How many {items} are on the truck?",
    "{name} spends {A} minutes on homework and {B} minutes on reading. How many minutes in total?",
]

SUBTRACTION_TEMPLATES = [
    "{name} has {A} {items}. {pronoun} gives away {B}. How many {items} does {name} have left?",
    "{name} has ${A}. {pronoun} spends ${B}. How much money does {name} have left?",
    "There are {A} {items} in a basket. {name} takes {B}. How many {items} are left?",
    "A store has {A} {items}. It sells {B}. How many {items} are left in the store?",
    "{name} has {A} {items} and loses {B}. How many {items} does {name} have now?",
    "A bus has {A} passengers. At the next stop {B} get off. How many passengers are on the bus?",
    "{name} bakes {A} {items}. {name2} eats {B}. How many {items} are left?",
    "A jar has {A} {items}. {name} removes {B}. How many {items} are in the jar now?",
    "{name} has {A} pages left to read. {pronoun} reads {B}. How many pages are left?",
    "A farm has {A} animals. The farmer sells {B}. How many animals are left on the farm?",
    "{name} has {A} {items} in a collection. {pronoun} trades away {B}. How many are left?",
    "There are {A} students in a class. Then {B} go home. How many students are left?",
    "{name} has ${A} in the bank. {pronoun} withdraws ${B}. How much is left in the bank?",
    "A warehouse has {A} {items}. A truck takes {B}. How many {items} remain?",
    "{name} picks {A} {items}. {pronoun} drops {B} on the way home. How many does {name} keep?",
    "A parking lot has {A} cars. Then {B} cars leave. How many cars are still in the lot?",
    "{name} makes {A} {items}. {pronoun} gives {B} to {name2}. How many does {name} keep?",
    "A tree has {A} leaves. The wind blows off {B}. How many leaves are left on the tree?",
    "{name} has {A} minutes of free time. {pronoun} spends {B} minutes studying. How many minutes are left?",
    "A box contains {A} {items}. {name} uses {B}. How many {items} are left in the box?",
    "A town has {A} houses. A storm destroys {B}. How many houses are left?",
    "{name} has {A} {items}. {pronoun} donates {B} to charity. How many {items} does {name} have left?",
    "A library has {A} books. Students borrow {B}. How many books are left in the library?",
    "{name} starts with {A} points. {pronoun} loses {B} points. How many points does {name} have?",
    "There are {A} {items} in a bag. {name} takes out {B}. How many {items} are in the bag?",
    "{name} has {A} tickets. {pronoun} uses {B} to enter rides. How many tickets are left?",
    "A pond has {A} fish. A fisherman catches {B}. How many fish are left in the pond?",
    "{name} has {A} {items}. {pronoun} breaks {B} of them. How many {items} are still good?",
    "A shop has {A} {items} in stock. Customers buy {B}. How many {items} are left?",
    "A truck carries {A} {items}. Workers unload {B}. How many {items} are still on the truck?",
    "{name} has {A} photos. {pronoun} deletes {B}. How many photos does {name} have now?",
    "A school has {A} computers. It donates {B}. How many computers does the school have left?",
    "{name} has {A} coins. {pronoun} spends {B} coins at the arcade. How many coins are left?",
    "A restaurant has {A} plates. {B} plates break. How many plates are left?",
    "{name} downloads {A} songs. {pronoun} removes {B}. How many songs does {name} have?",
    "There are {A} people at a party. Then {B} leave. How many people are still at the party?",
    "A factory makes {A} {items}. Quality control rejects {B}. How many good {items} are left?",
    "{name} has {A} stickers. {pronoun} gives {B} to {name2}. How many stickers does {name} have?",
    "A garden has {A} flowers. {name} picks {B}. How many flowers are left in the garden?",
    "{name} has {A} {items} on a shelf. {pronoun} packs {B} into a box. How many are still on the shelf?",
]

MULTIPLICATION_TEMPLATES = [
    "{name} has {A} {containers} with {B} {items} each. How many {items} in total?",
    "There are {A} rows with {B} {items} in each row. How many {items} are there?",
    "{name} buys {A} packs of {items}. Each pack has {B}. How many {items} does {name} have?",
    "A school has {A} classrooms. Each classroom has {B} desks. How many desks are there?",
    "{name} works {A} hours a day for {B} days. How many hours does {name} work in total?",
    "A parking lot has {A} rows. Each row fits {B} cars. How many cars can the lot hold?",
    "{name} gives {B} {items} to each of {A} {groups}. How many {items} does {name} give out?",
    "A building has {A} floors. Each floor has {B} windows. How many windows does the building have?",
    "{name} reads {B} pages every day for {A} days. How many pages does {name} read?",
    "There are {A} tables. Each table has {B} chairs. How many chairs are there in total?",
    "A factory produces {B} {items} per hour. It runs for {A} hours. How many {items} are produced?",
    "{name} plants {A} rows of flowers. Each row has {B} flowers. How many flowers did {name} plant?",
    "A hotel has {A} rooms. Each room has {B} beds. How many beds does the hotel have?",
    "{name} earns ${B} per hour. {pronoun} works for {A} hours. How much does {name} earn?",
    "There are {A} teams. Each team has {B} players. How many players are there in total?",
    "A train has {A} cars. Each car has {B} seats. How many seats are on the train?",
    "{name} has {A} shelves. Each shelf holds {B} books. How many books can {name} store?",
    "A baker makes {A} trays of {items}. Each tray has {B}. How many {items} does the baker make?",
    "{name} runs {B} laps every day for {A} days. How many laps does {name} run in total?",
    "There are {A} bags. Each bag contains {B} {items}. How many {items} are there altogether?",
    "A garden has {A} rows. Each row has {B} plants. How many plants are in the garden?",
    "{name} puts {B} {items} in each of {A} {containers}. How many {items} does {name} use?",
    "A store sells {B} {items} per day for {A} days. How many {items} does the store sell?",
    "{name} has {A} friends. {pronoun} gives each friend {B} {items}. How many {items} does {name} give?",
    "A truck makes {A} trips. Each trip carries {B} {items}. How many {items} does the truck carry?",
    "There are {A} boxes. Each box weighs {B} kg. What is the total weight?",
    "{name} practices piano {B} minutes a day for {A} days. How many minutes total?",
    "A library has {A} sections. Each section has {B} shelves. How many shelves are there?",
    "{name} packs {A} {containers} with {B} {items} each. How many {items} does {name} pack?",
    "A farm has {A} fields. Each field has {B} trees. How many trees are on the farm?",
    "{name} saves ${B} every week for {A} weeks. How much does {name} save?",
    "A cinema has {A} screens. Each screen has {B} seats. How many seats does the cinema have?",
    "{name} drinks {B} glasses of water a day for {A} days. How many glasses in total?",
    "There are {A} cartons. Each carton holds {B} bottles. How many bottles are there?",
    "A company has {A} offices. Each office has {B} employees. How many employees total?",
    "{name} walks {B} km every day for {A} days. How many km does {name} walk?",
    "A bookshelf has {A} rows. Each row fits {B} books. How many books fit on the bookshelf?",
    "{name} fills {A} jars with {B} {items} each. How many {items} does {name} use?",
    "A neighborhood has {A} streets. Each street has {B} houses. How many houses total?",
    "{name} makes {A} trips to the store. Each trip {pronoun} buys {B} {items}. How many {items} total?",
]

DIVISION_TEMPLATES = [
    "{name} has {A} {items} to share equally among {B} {groups}. How many {items} does each group get?",
    "{name} splits {A} {items} into {B} equal piles. How many {items} are in each pile?",
    "A teacher has {A} {items} for {B} students. Each student gets the same amount. How many each?",
    "{name} packs {A} {items} into {containers}. Each {container} holds {B}. How many {containers} are needed?",
    "A factory makes {A} {items} in {B} hours. How many {items} does it make per hour?",
    "{name} drives {A} km in {B} hours. What is the speed in km per hour?",
    "There are {A} seats arranged in {B} equal rows. How many seats are in each row?",
    "{name} has ${A} to split equally among {B} {groups}. How much does each group get?",
    "A farm divides {A} acres into {B} equal fields. How many acres is each field?",
    "{name} reads {A} pages over {B} days, reading the same amount each day. How many pages per day?",
    "A store divides {A} {items} equally onto {B} shelves. How many {items} per shelf?",
    "{name} cuts a rope that is {A} meters into {B} equal pieces. How long is each piece?",
    "There are {A} {items} to be packed into {containers} of {B} each. How many {containers} are needed?",
    "{name} earns ${A} over {B} weeks. How much does {name} earn per week?",
    "A bakery makes {A} {items} and puts {B} in each box. How many boxes are needed?",
    "A bus carries {A} students in {B} equal trips. How many students per trip?",
    "{name} has {A} photos to put into {B} albums equally. How many photos per album?",
    "A garden has {A} plants in {B} equal rows. How many plants per row?",
    "{name} walks {A} km over {B} days. How many km per day?",
    "A company ships {A} {items} in {B} equal shipments. How many {items} per shipment?",
    "{name} divides {A} {items} equally into {B} {containers}. How many in each?",
    "There are {A} minutes of video split into {B} equal parts. How many minutes per part?",
    "A pool holds {A} liters. It is filled by {B} equal buckets. How many liters per bucket?",
    "{name} shares {A} {items} equally with {B} friends. How many does each friend get?",
    "A truck delivers {A} {items} to {B} stores equally. How many {items} per store?",
    "{name} spends ${A} equally over {B} months. How much per month?",
    "A recipe makes {A} servings. {name} wants to split it into {B} meals. How many servings per meal?",
    "There are {A} books to arrange on {B} shelves equally. How many books per shelf?",
    "{name} has {A} hours of work to spread over {B} days. How many hours per day?",
    "A warehouse has {A} {items} in {B} equal stacks. How many {items} per stack?",
]

MUL_ADD_TEMPLATES = [
    "{name} has {A} {containers} with {B} {items} each. {pronoun} finds {C} more. How many {items} in total?",
    "A store sells {A} packs of {B} {items}. Then {C} extra {items} are added. How many {items} total?",
    "{name} works {A} days earning ${B} per day. {pronoun} gets a ${C} bonus. How much total?",
    "There are {A} rows of {B} chairs. Someone adds {C} extra chairs. How many chairs total?",
    "{name} buys {A} boxes of {B} {items}. {name2} gives {name} {C} more. How many {items} total?",
    "A farmer plants {A} rows of {B} seeds. Then plants {C} more seeds. How many seeds total?",
    "{name} reads {B} pages a day for {A} days. Then reads {C} more pages. How many pages total?",
    "A hotel has {A} floors with {B} rooms each. It builds {C} new rooms. How many rooms total?",
    "{name} earns ${B} per hour for {A} hours. {pronoun} gets a ${C} tip. How much total?",
    "A factory makes {A} batches of {B} {items}. Workers add {C} more. How many {items} total?",
    "{name} has {A} groups of {B} {items}. {pronoun} buys {C} more. How many {items} altogether?",
    "A parking lot has {A} rows of {B} spaces. They add {C} new spaces. How many spaces total?",
    "{name} bakes {A} trays of {B} cookies. {pronoun} makes {C} extra. How many cookies total?",
    "A school has {A} classes of {B} students. Then {C} new students enroll. How many students total?",
    "There are {A} shelves with {B} books each. {name} adds {C} more books. How many books total?",
]

MUL_SUB_TEMPLATES = [
    "{name} has {A} {containers} with {B} {items} each. {pronoun} eats {C}. How many {items} are left?",
    "A shop has {A} boxes of {B} {items}. It sells {C}. How many {items} are left?",
    "{name} makes {A} batches of {B} {items}. {C} are broken. How many good {items} are left?",
    "There are {A} rows of {B} seats. {C} seats are removed. How many seats remain?",
    "{name} buys {A} packs of {B} {items}. {pronoun} gives away {C}. How many {items} does {name} keep?",
    "A farm has {A} fields with {B} trees each. A storm knocks down {C}. How many trees are left?",
    "{name} earns ${B} per day for {A} days. {pronoun} spends ${C}. How much is left?",
    "A bakery makes {A} trays of {B} muffins. Customers buy {C}. How many muffins are left?",
    "{name} collects {A} sets of {B} {items}. {pronoun} loses {C}. How many {items} remain?",
    "A library has {A} shelves of {B} books. Students borrow {C}. How many books are left?",
    "{name} has {A} bags with {B} {items} each. {pronoun} donates {C}. How many {items} are left?",
    "A warehouse stores {A} pallets of {B} {items}. A truck takes {C}. How many {items} remain?",
    "{name} picks {A} baskets of {B} berries. {pronoun} eats {C} berries. How many are left?",
    "A garden has {A} rows of {B} flowers. {name} picks {C}. How many flowers are left?",
    "There are {A} boxes of {B} {items}. Workers use {C}. How many {items} are left?",
]

ADD_MUL_TEMPLATES = [
    "{name} has {A} {items} and gets {B} more. {pronoun} then doubles that by multiplying by {C}. How many?",
    "A store has {A} {items}. It receives {B} more. Then orders {C} times that amount. How many total?",
    "{name} saves ${A} and earns ${B} more. {pronoun} invests and it grows {C} times. How much total?",
    "A garden has {A} plants. {name} adds {B} more. Each plant produces {C} fruits. How many fruits?",
    "{name} has {A} points. {pronoun} earns {B} more. The score is multiplied by {C}. What is the score?",
    "There are {A} workers and {B} join. Each worker makes {C} {items}. How many {items} total?",
    "{name} collects {A} cards and finds {B} more. Each card is worth ${C}. How much are they worth?",
    "A team has {A} members and {B} join. Each member brings {C} {items}. How many {items} total?",
    "{name} has {A} seeds and buys {B} more. Each seed grows {C} flowers. How many flowers total?",
    "A class has {A} boys and {B} girls. Each student brings {C} {items}. How many {items} total?",
]

ADD_SUB_TEMPLATES = [
    "{name} has {A} {items}. {pronoun} gets {B} more, then gives away {C}. How many {items} are left?",
    "A store has {A} {items}. A delivery brings {B} more. Customers buy {C}. How many are left?",
    "{name} has ${A}. {pronoun} earns ${B} more, then spends ${C}. How much is left?",
    "There are {A} birds in a tree. {B} more arrive, then {C} fly away. How many birds are left?",
    "{name} picks {A} {items}. {name2} gives {name} {B} more. {name} eats {C}. How many are left?",
    "A bus has {A} passengers. At one stop {B} get on and {C} get off. How many are on the bus?",
    "{name} has {A} pages to read. {pronoun} reads {B} but adds {C} to the list. Wait, {name} has {A} pages, adds {B} more, then reads {C}. How many are left?",
    "A pond has {A} fish. {B} new fish are added. A fisherman catches {C}. How many fish are left?",
    "{name} has {A} stickers. {pronoun} buys {B} more, then trades {C} away. How many are left?",
    "A shelf has {A} {items}. {name} adds {B} and removes {C}. How many {items} are on the shelf?",
]

SUB_MUL_TEMPLATES = [
    "{name} has {A} {items}. {pronoun} gives away {B}. Then each remaining item splits into {C}. How many total?",
    "A store has {A} {items}. It returns {B}. The rest are sold in packs of {C}. Wait, each of the remaining {items} is packaged into {C} pieces. How many pieces?",
    "{name} has ${A}. {pronoun} spends ${B}. Then {pronoun} multiplies the rest by investing {C} times. How much?",
    "There are {A} teams. {B} teams drop out. Each remaining team has {C} players. How many players total?",
    "A farm has {A} fields. {B} fields are sold. Each remaining field has {C} trees. How many trees?",
    "{name} has {A} bags. {pronoun} loses {B}. Each remaining bag has {C} {items}. How many {items}?",
    "A school has {A} classes. {B} classes are cancelled. Each remaining class has {C} students. How many students?",
    "{name} picks {A} flowers. {pronoun} gives {B} away. {pronoun} puts the rest into bouquets of {C}. Wait, each remaining flower is split into {C} petals. How many petals?",
    "A library has {A} sections. {B} are closed. Each open section has {C} books. How many books total?",
    "There are {A} boxes. {B} are removed. Each remaining box has {C} {items}. How many {items}?",
]

DIV_ADD_TEMPLATES = [
    "{name} splits {A} {items} equally among {B} friends. Then each friend gets {C} extra. How many does each have?",
    "A company earns ${A} over {B} months. Then gets a ${C} bonus per month. How much per month total?",
    "{name} divides {A} pages into {B} equal chapters. Then adds {C} pages to each. How many pages per chapter?",
    "A farmer splits {A} acres into {B} fields. Each field gains {C} extra acres. How many acres per field?",
    "{name} has {A} {items} shared among {B} boxes. {pronoun} adds {C} more to each box. How many per box?",
    "A school divides {A} books among {B} classes. Each class gets {C} extra books. How many per class?",
    "{name} splits ${A} between {B} accounts. Then deposits ${C} more in each. How much per account?",
    "A bakery divides {A} {items} into {B} bags. Then adds {C} to each bag. How many per bag?",
    "A truck carries {A} {items} for {B} stores. Each store also receives {C} extra. How many per store?",
    "There are {A} tasks split among {B} workers. Each worker gets {C} extra tasks. How many per worker?",
]

CMP_TEMPLATES = [
    "{name} has {A} {items}. {name2} has {B} {items}. Does {name} have more {items} than {name2}?",
    "Team A scores {A} points. Team B scores {B} points. Does Team A have more points?",
    "{name} has ${A}. {name2} has ${B}. Does {name} have more money than {name2}?",
    "{name} reads {A} books. {name2} reads {B} books. Does {name} read more than {name2}?",
    "A jar has {A} {items}. A box has {B} {items}. Does the jar have more {items}?",
    "{name} runs {A} laps. {name2} runs {B} laps. Does {name} run more laps than {name2}?",
    "Store A sells {A} {items}. Store B sells {B} {items}. Does Store A sell more?",
    "{name} collects {A} {items}. {name2} collects {B}. Does {name} collect more than {name2}?",
    "Class A has {A} students. Class B has {B} students. Does Class A have more students?",
    "{name} saves ${A}. {name2} saves ${B}. Does {name} save more than {name2}?",
    "A garden has {A} roses. Another garden has {B} roses. Does the first garden have more?",
    "{name} walks {A} km. {name2} walks {B} km. Does {name} walk farther than {name2}?",
    "Shelf A holds {A} books. Shelf B holds {B} books. Does Shelf A hold more?",
    "{name} bakes {A} {items}. {name2} bakes {B}. Does {name} bake more than {name2}?",
    "A pond has {A} fish. A lake has {B} fish. Does the pond have more fish?",
]

CMP_SUB_TEMPLATES = [
    "{name} has {A} {items}. {pronoun} gives away {B}. {name2} has {C} {items}. Does {name} have more than {name2}?",
    "{name} has ${A}. {pronoun} spends ${B}. {name2} has ${C}. Does {name} have more money?",
    "A store has {A} {items}. It sells {B}. Another store has {C}. Does the first store have more?",
    "{name} picks {A} flowers. {pronoun} gives {B} to {name2}. {name2} already had {C}. Does {name} have more?",
    "A bus has {A} passengers. {B} get off. Another bus has {C} passengers. Does the first bus have more?",
    "{name} earns ${A}. {pronoun} spends ${B}. {name2} has ${C}. Does {name} have more?",
    "A jar has {A} {items}. {name} takes {B}. A box has {C} {items}. Does the jar have more?",
    "{name} bakes {A} cookies. {pronoun} eats {B}. {name2} has {C} cookies. Does {name} have more?",
    "A tree has {A} leaves. {B} fall off. Another tree has {C} leaves. Does the first tree have more?",
    "{name} has {A} stickers. {pronoun} trades {B}. {name2} has {C} stickers. Does {name} have more?",
    "A library has {A} books. Students borrow {B}. Another library has {C}. Does the first have more?",
    "{name} has {A} points. {pronoun} loses {B}. {name2} has {C} points. Does {name} have more?",
    "A farm has {A} animals. {B} are sold. A neighbor has {C} animals. Does the farm have more?",
    "{name} has {A} {items}. {pronoun} breaks {B}. {name2} has {C}. Does {name} have more {items}?",
    "A parking lot has {A} cars. {B} leave. Another lot has {C} cars. Does the first lot have more?",
]

CMP_MUL_TEMPLATES = [
    "{name} has {A} {containers} with {B} {items} each. {name2} has {C} {items}. Does {name} have more?",
    "A store sells {A} packs of {B} {items}. Another store has {C} {items}. Does the first store have more?",
    "{name} works {A} days earning ${B} per day. {name2} has ${C}. Does {name} earn more?",
    "A farm has {A} rows of {B} trees. A park has {C} trees. Does the farm have more trees?",
    "{name} reads {B} pages a day for {A} days. {name2} reads {C} pages total. Does {name} read more?",
    "A factory makes {A} batches of {B} {items}. Another factory makes {C}. Does the first make more?",
    "{name} saves ${B} per week for {A} weeks. {name2} has ${C}. Does {name} save more?",
    "A garden has {A} rows of {B} flowers. Another garden has {C} flowers. Does the first have more?",
    "{name} fills {A} jars with {B} {items} each. {name2} has {C} {items}. Does {name} have more?",
    "A hotel has {A} floors with {B} rooms each. Another hotel has {C} rooms. Does the first have more?",
]
